### ISSUE TITLE
Show inline microphone

### ISSUE THREAD

**Issue by kenguest** [cweiske/headphoneindicator#3]
It would be useful if the indicator also detected if an inline microphone is included, and presented that information cleanly.

**Comment by davidhedlund** [comment]
Yes, that would be a useful feature to make sure that a [microphone blocker](https://en.wikipedia.org/wiki/Microphone_blocker) is working and properly mounted, and that the smartphones headset jack switch is not broken.

Perhaps you want to rename the program to __headsetindicator__ if you implement this.

**Comment by cweiske** [comment]
https://developer.android.com/reference/android/media/AudioManager#ACTION_HEADSET_PLUG

> microphone - 1 if headset has a microphone, 0 otherwise

**Comment by davidhedlund** [comment]
> https://developer.android.com/reference/android/media/AudioManager#ACTION_HEADSET_PLUG
> 
> > microphone - 1 if headset has a microphone, 0 otherwise

Thank you for your interest in this and for your contribution to free software.

**Comment by davidhedlund** [comment]
Can you please rename the title of this issue to "Inline microphone connector indicator" or something?

**Comment by davidhedlund** [comment]
Nice.

**Comment by cweiske** [comment]
Headset indicator is implemented in [v1.1.0](https://github.com/cweiske/headphoneindicator/releases/tag/v1.1.0)

**Comment by davidhedlund** [comment]
> Headset indicator is implemented in v1.1.0

Thank you very much!
