### ISSUE TITLE
Version 1.1.0: Samsung S10 plus not working correctly

### ISSUE THREAD

**Issue by Arvaarad** [cweiske/headphoneindicator#8]
Since updating to 1.1.0 the app doesnt seem to run well in the background anymore. I have to open the app everytime for the icon to show in the notification area and is stays long there until the app is closed and re-opened.

**Comment by cweiske** [comment]
S10 is from Samsung, which known for breaking background apps. See https://dontkillmyapp.com/ and try the instructions there. I can't help you.

**Comment by Arvaarad** [comment]
The previous version worked fine so I reinstalled that.
