### ISSUE TITLE
More (privacy) indicators?

### ISSUE THREAD

**Issue by TPS** [cweiske/headphoneindicator#9]
@cweiske Would you be interested in adding more, privacy-related indicators, like for current camera/microphone/location?  [Privacy Indicator](https://github.com/NitishGadangi/Privacy-Indicator-App) is abandoned since 2021, but still _used_ to work until most recent Android security update.  You're currently developing HPI conceptually similar, so maybe this is close enough for some additions?

**Comment by cweiske** [comment]
No, I am not interested.
